products = [
    {"id": 1, "name": "Running Shoes", "price": 3000, "image": "👟"},
    {"id": 2, "name": "Backpack", "price": 2000, "image": "🎒"},
    {"id": 3, "name": "Wireless Headphones", "price": 5000, "image": "🎧"},
    {"id": 4, "name": "Smart Watch", "price": 7000, "image": "⌚"},
    {"id": 5, "name": "Sunglasses", "price": 1500, "image": "🕶️"},
    {"id": 6, "name": "Laptop Sleeve", "price": 1200, "image": "💻"},
    {"id": 7, "name": "Water Bottle", "price": 500, "image": "🍼"},
    {"id": 8, "name": "Gaming Mouse", "price": 2500, "image": "🖱️"},
    {"id": 9, "name": "Mechanical Keyboard", "price": 6000, "image": "⌨️"},
    {"id": 10, "name": "Bluetooth Speaker", "price": 3500, "image": "🔊"},
    {"id": 11, "name": "Power Bank", "price": 1800, "image": "🔋"},
    {"id": 12, "name": "Phone Case", "price": 800, "image": "📱"},
    {"id": 13, "name": "Desk Lamp", "price": 2200, "image": "💡"},
    {"id": 14, "name": "Office Chair", "price": 9000, "image": "🪑"},
    {"id": 15, "name": "Notebook", "price": 300, "image": "📓"},
    {"id": 16, "name": "Pen Set", "price": 400, "image": "🖊️"},
    {"id": 17, "name": "Travel Pillow", "price": 1000, "image": "🛏️"},
    {"id": 18, "name": "Fitness Band", "price": 2500, "image": "📟"},
    {"id": 19, "name": "Camera Tripod", "price": 4500, "image": "📷"},
    {"id": 20, "name": "DSLR Camera", "price": 45000, "image": "📸"},
    {"id": 21, "name": "Tablet", "price": 20000, "image": "📲"},
    {"id": 22, "name": "Monitor", "price": 12000, "image": "🖥️"},
    {"id": 23, "name": "USB Hub", "price": 900, "image": "🔌"},
    {"id": 24, "name": "External Hard Drive", "price": 6500, "image": "💾"},
    {"id": 25, "name": "Router", "price": 3000, "image": "📡"},
    {"id": 26, "name": "Smart Bulb", "price": 1200, "image": "💡"},
    {"id": 27, "name": "VR Headset", "price": 15000, "image": "🕶️"},
    {"id": 28, "name": "Electric Kettle", "price": 1800, "image": "🍵"},
    {"id": 29, "name": "Coffee Maker", "price": 5000, "image": "☕"},
    {"id": 30, "name": "Air Purifier", "price": 10000, "image": "🌬️"}
]